name: Test-Build
on:
  push:
    branches:
    - main

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Install Node
      uses: actions/setup-node@v4
    - name: Install newman
      run: "npm install -g newman \nnpm install -g newman-reporter-htmlextra\n"
      # - name: Make Directory for results
    - name: Run Test
      # run: mkdir -p results
      run: newman run ./petstore.collection.json -r htmlextra --reporter-htmlextra-export ./results/htmlreport.html
    - name: Output the run Details
      uses: actions/upload-artifact@v4
      with:
        name: RunReports
        path: testResults
