name: Test-Build
on:
  push:
    branches:
    - main

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version: 'latest'

    - name: Install newman
      run: |
        npm install -g newman
        npm install -g newman-reporter-htmlextra

    - name: Make Directory for results
      run: mkdir -p testResults

    - name: Run Test
      run: |
        newman run petstore.collection.json \
        -r htmlextra --reporter-htmlextra-export testResults/htmlreport.html \
        --reporter-htmlextra-darkTheme > testResults/runreport1.html
      continue-on-error: true
    
    - name: Add, commit and push changes
      run: |
        git config --local user.email "{{ secrets.USER_EMAIL }}"
        git config --local user.name "{{ secrets.USER_NAME }}"
        git add testResults/htmlreport.html
        git commit -m "Add generated htmlreport"
        git push 

    - name: Output the run Details
      uses: actions/upload-artifact@v4
      with:
        name: RunReports
        path: testResults
