name: Test-Build
on:
  push:
    branches:
    - main

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version: 'latest'

    - name: Install newman
      run: |
        npm install -g newman
        npm install -g newman-reporter-htmlextra

    - name: Make Directory for results
      run: mkdir -p testResults

    - name: Run Test
      run: |
        newman run petstore.collection.json \
        -r htmlextra --reporter-htmlextra-export testResults/htmlreport.html \
        --reporter-htmlextra-darkTheme > testResults/runreport1.html
      continue-on-error: true

    - name: Output the run Details
      uses: actions/upload-artifact@v4
      with:
        name: RunReports
        path: testResults 

    - name: Test marketplace action
      uses: PavanMudigonda/html-reporter-github-pages@v1.0
      id: test-report
      with:
        test_results: testResults
        gh_pages: gh-pages
        results_history: results-history

    - name: Publish Github Pages
      if: ${{ always() }}
      uses: peaceiris/actions-gh-pages@v3.8.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: results-history
        keep_files: true 