name: Test-Build
on:
  push:
    branches:
    - main

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version: latest
    - name: Install newman
      run: "npm install -g newman \nnpm install -g newman-reporter-htmlextra\n"
    - name: Make Directory for results
      run: mkdir -p testResults

    - name: Run Postman collection
      run: |
        newman run  Postman-newman-ghActions/petstore.collection.json  -r htmlextra --reporter-htmlextra-export testResults/htmlreport.html --reporter-htmlextra-darkThem > testResults/runreport1.html

    - name: Output the run Details
      uses: actions/upload-artifact@v4
      with:
        name: RunReports
        path: testResults
