name: ERP Postman Automation API Test

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Step 1 Check version Newman and Node
        run: |
          newman --version
          node --version

      - name: Step 2 Install Newman-Reporter-HtmlExtra
        run: npm install -g newman-reporter-htmlextra

      - name: Create dir
        run: mkdir -p docs

      - name: Step 3 Execute collection
        run: newman run petstore.collection.json --reporter-htmlextra-export ./docs/index.html

      - name: List files in docs
        if: ${{ always() }}
        run: ls -la ./docs

      - name: Step 4 Archive Production artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: ./docs/index.html

      - name: Step 5 Deploy to GitHub Pages
        if: ${{ always() }}
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
